# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate boomenv
#
name: boomenv
channels:
  - conda-forge
dependencies:
  - jupyter
  - pandas
  - requests
  - scikit-learn
  - seaborn
  - missingno
  - plotly
  - python-kaleido
